---
title: "Estudio Longitudinal Social de Chile (ELSOC)2"
description: |
  Trabajaremos con las tres olas del Estudio Longitudinal Social de Chile (ELSOC) del Centro de Estudios de Conflicto y Cohesión Social (COES).
author:
  - name: Francisco Guzmán
    #url: {}
date: 04-15-2021
output: 
  distill::distill_article:
    code_folding: false
    toc: true
    number_sections: true
    toc_float: true
    toc_depth: 4
categories:
  - haven
#preview: "plot.png"
draft: true
---

<style>
body {
text-align: justify}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Librerías 

```{r}
library(haven)
library(plyr)
library(dplyr)
library(naniar)
library(expss)
library(pastecs)
library(ggplot2)
library(summarytools)
library(table1) 

```

# Base de Datos

```{r}
base <- readRDS("elsoc.rds")

```

## Nuevo DataFrame
Creamos un nuevo *DataFrame* con las variables que utilizaremos.

```{r}
elsoc <- base %>% 
  select(idencuesta, ola,
         d03_01, d03_02, d04_01, d04_02
         )
```


## Creación de variables

```{r}
#salario percibido en $ millones
elsoc$sp_gerente <- d03_01/1000000
elsoc$sp_obrero <- d03_02/1000000

#salario justo en $ millones
elsoc$sj_gerente <- d04_01/1000000
elsoc$sj_obrero <- d04_02/1000000

#brecha percibida
elsoc$bp <-  elsoc$sp_gerente/elsoc$sp_obrero
elsoc$bp_ln <-  log(elsoc$sp_gerente/elsoc$sp_obrero)

#brecha justa
elsoc$bj <-  elsoc$sj_gerente/elsoc$sj_obrero
elsoc$bj_ln <-  log(elsoc$sj_gerente/elsoc$sj_obrero)

elsoc[sapply(elsoc, is.infinite)] <- NA #valores infinitos como NA
elsoc[sapply(elsoc, is.nan)] <- NA #NaN como NA

```

## Etiquetamos variables
```{r, results='hide'}
elsoc = apply_labels(elsoc,
                      sp_gerente = "Salario percibido: Gerente gran empresa ($MM)",
                     sp_obrero = "Salario Percibido: Obrero no calificado ($MM)",
                     sj_gerente = "Salario justo: Gerente gran empresa ($MM)",
                     sj_obrero = "Salario justo: Obrero no calificado ($MM)",
                     bp = "Brecha Percibida",
                     bp_ln = "Brecha Percibida (ln)",
                     bj = "Brecha Justa",
                     bj_ln = "Brecha Justa (ln)"
                     )
'
Otra opción es:
label(elsoc$sp_gerente) <- "Salario percibido: Gerente gran empresa ($MM)"
'

```

# Outliers
## Revisión
```{r}
aux_outliers <- elsoc %>% 
  select(idencuesta, ola, sp_gerente,sp_obrero,sj_gerente,sj_obrero)

aux_outliers$ln_sp_gerente <- log(elsoc$sp_gerente)
aux_outliers$ln_sj_gerente <- log(elsoc$sj_gerente)

attach(aux_outliers)
par(mfrow=c(2,2))
plot(sp_gerente)
plot(sj_gerente)
plot(ln_sp_gerente)
plot(ln_sj_gerente)

```

## Eliminación
```{r}
df <- elsoc[!(elsoc$idencuesta %in% c("3101041","3301091", "3301183", "3301113", "13115035","13115022") 
       & elsoc$ola == 1), 
       ]

```

# Estadística Descriptiva

```{r}
table1(~ sp_gerente + sp_obrero + sj_gerente +  sj_obrero + bp + bj | ola, 
       data = df,
       overall = F,
       render.continuous=c("Media (Desv. est.)"="Mean (SD)", "Mediana [Rango]"="Median [Min, Max]", "Obs."="N"),
       render.missing = NULL,
       topclass="Rtable1-zebra",
       footnote = "Fuente: Elaboración propia en base a datos de Estudio Longitudinal Social de Chile (ELSOC)",
       caption = "Salario Percibido, Salario Justo y Brechas"
       )
```



# Referencias

* [Replacing values with NA](https://cran.r-project.org/web/packages/naniar/vignettes/replace-with-na.html)


