---
title: "rbind.fill para armado de bases"
description: |
  Juntaremos las tres olas del Estudio Longitudinal Social de Chile (ELSOC) del Centro de Estudios de Conflicto y Cohesión Social (COES) con el comando rbind.fill.
author:
  - name: Francisco Guzmán
    #url: {}
date: 04-14-2021
output: 
  distill::distill_article:
    toc: true
    number_sections: true
    toc_float: true
    toc_depth: 4
categories:
  - ELSOC

#preview: "plot.png"
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, echo = TRUE)
```

# Librerías 

```{r}
library(haven)
library(plyr)
library(dplyr)
library(naniar)

```

# Base de Datos
## Importamos
Obtenemos las bases en formato *.RData* desde [dataverse.harvard.edu](https://dataverse.harvard.edu/dataverse/coes_data_repository?q=&types=datasets&fq0=subtreePaths%3A%22%2F3130692%22&fq1=dvObjectType%3A%28datasets+OR+files%29&sort=dateSort&order=desc&page=1). Luego, las importamos.

```{r}
load("ELSOC_W01_v4.00_R.RData")
load("ELSOC_W02_v3.00_R.RData")
load("ELSOC_W03_v2.00_R.RData")

```

## rbind.fill
Combinamos las tres bases con el comando **rbind.fill**(como *append* en stata):

```{r}
elsoc <- as.data.frame(rbind.fill(elsoc_2016, elsoc_2017, elsoc_2018))

```

## Guardamos Base
Guardamos la base con:

```{r}
saveRDS(elsoc, "elsoc.rds")

```


# Referencias
* [dataverse.harvard.edu](https://dataverse.harvard.edu/dataverse/coes_data_repository?q=&types=datasets&fq0=subtreePaths%3A%22%2F3130692%22&fq1=dvObjectType%3A%28datasets+OR+files%29&sort=dateSort&order=desc&page=1)